services:
  app:
    build: .
    restart: always
    volumes:
      # Связываем папку на сервере с папкой внутри контейнера
      - ./database:/app/database
    # Если приложению нужен порт (например, Flask/FastAPI), раскомментируй:
    # ports:
    #   - "80:8000"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    volumes:
      # Пробрасываем ту же папку с базой, чтобы Adminer её видел
      - ./database:/var/www/html/db_files
volumes:
  db_data: