version: '3.8'

services:
  # 1. Ваш Python проект
  app:
    build: .
    ports:
      - "80:8000"
    volumes:
      # Пробрасываем папку с базой данных, чтобы она сохранялась на сервере
      - ./database:/app/data 
    environment:
      - DB_PATH=/app/data/my_database.db # Путь к файлу внутри контейнера
    depends_on:
      - db

  # 2. База данных (MariaDB остается, если она вам нужна параллельно)
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
      MYSQL_DATABASE: cars
    volumes:
      - db_data:/var/lib/mysql

  # 3. Adminer (Заменяет phpMyAdmin)
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    volumes:
      # ВАЖНО: подключаем ту же папку с файлом .db, что и у приложения 'app'
      - ./database:/var/www/html/db_files:ro